### ISSUE TITLE
Feature request: Auto-Restart

### ISSUE THREAD

**Issue by Henner7** [opendata-stuttgart/sensors-software#752]
In a weak Wifi the connection gets frequently lost. In my usecase the sensor does not reconnect to Wifi automatically again. Usually I get an email reminder after one day and then I need to re-start the sensor manually by disconnecting the power supply.

**Feature request:**
Add an option in the firmware: "Restart sensor each xxx hours", allow the user to set value between 0...999.

**Expected behaviour:**
When the restart value is set to 0, not automated restart is done. Otherwise the sensor is restarted after the specified number of hours.

**Used hardware:** ESP8266 with Feinstaub sensor and DHT sensor.

**Comment by irukard** [comment]
In NAMF (nettigo/namf) we implemented network watchdog which restart sensor if three 10-ping tests fail. https://github.com/nettigo/namf/tree/master/src/sensors/network_watchdog

**Comment by dirkmueller** [comment]
@Henner7 well, it is supposed to automatically reconnect on wifi loss. any chance you can capture the serial output while this happens? would be great for tracing this down..

**Comment by irukard** [comment]
Hint: Sensors might struggle with WPA2 implementation in MikroTik routers.

**Comment by ricki-z** [comment]
@irukard this isn't related to this feature request. If this is an issue please open a new one.

**Comment by Henner7** [comment]
> @Henner7 well, it is supposed to automatically reconnect on wifi loss. any chance you can capture the serial output while this happens? would be great for tracing this down..

Good morning, currently it disconnects every day. The reconnection can be re-established by either re-starting the sensor or by re-starting the Wifi. This is really strange. Unfortunately I cannot connect the serial output as long the sensor is mounted outside in the garden. You see that my original request is not about automatic reconnection but it is about timed re-start of the sensor indest.

**Comment by dirkmueller** [comment]
Technically the firmware already automatically restarts every 28 days, this is currently hard coded and cannot be changed. I was however thinking that instead of time based restart the wlan-resume behavior could be improved instead, as with a time based restart you will still be losing measurements until the time based restart hits, which is unwanted.

Also the firmware does on boot a self test off the sensors which increases wear. So a time restart with very short intervals is not useful. I hope you understand that as trying to solve the root cause might actually be better in the end.
