### ISSUE TITLE
Support for ECDSA

### ISSUE THREAD

**Issue by danielskowronski** [opendata-stuttgart/sensors-software#911]
Sensor firmware does not seem to support any elliptic curve ciphers. This is a little problematic as you can't use ECDSA certificate on InfluxDB (and can't hide it behind Cloudflare's free SSL) and may show some problems in future with other APIs - like with sensors.community when HTTPS is enabled.

See extracted TLS communication Client Hello:
```
Transport Layer Security
    TLSv1.2 Record Layer: Handshake Protocol: Client Hello
        Content Type: Handshake (22)
        Version: TLS 1.0 (0x0301)
        Length: 101
        Handshake Protocol: Client Hello
            Handshake Type: Client Hello (1)
            Length: 97
            Version: TLS 1.2 (0x0303)
            Random: 0000000049a5a77461e2ecc3614542ec5c5656da8f2f4f19fe99c49a1862b839
            Session ID Length: 0
            Cipher Suites Length: 8
            Cipher Suites (4 suites)
                Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA256 (0x003c)
                Cipher Suite: TLS_RSA_WITH_AES_256_CBC_SHA256 (0x003d)
                Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA (0x002f)
                Cipher Suite: TLS_RSA_WITH_AES_256_CBC_SHA (0x0035)
            Compression Methods Length: 1
            Compression Methods (1 method)
            Extensions Length: 48
            Extension: renegotiation_info (len=1)
            Extension: server_name (len=18)
            Extension: max_fragment_length (len=1)
            Extension: signature_algorithms (len=12)
```
and response from server with **ECDSA with SHA-256** certificate:
```
Transport Layer Security
    TLSv1.2 Record Layer: Alert (Level: Fatal, Description: Handshake Failure)
        Content Type: Alert (21)
        Version: TLS 1.2 (0x0303)
        Length: 2
        Alert Message
            Level: Fatal (2)
            Description: Handshake Failure (40)
```

**Comment by ricki-z** [comment]
Most certificates are RSA signed certs. And both InfluxDB and Cloudflare also support RSA certs. It's even the standard for Let'sEncrypt certs. So I think you are talking about ecliptic curve key exchange algorithms.
The problem is the available RAM and space for the firmware. We would need to use the BearSSL implementation included in the ESP8266 core for Arduino. But this would add so much in image size that we won't be able to implement OTA anymore.
It's not possible to limit the the cipher list (beside limiting it to the 4 algorithms we use) to save some space. And we aren't able to implement an own version for this.
So at the moment there is no chance to include more algorithms without removing other functions. (We also checked a minimum firmware with only the standard sensors and it would be to large to have OTA updates)
But if you can find any smaller implementation don't hesitate to tell us about it.
We may have a chance to add EC algorithms for an ESP32 implementation.
